spring:
  datasource:
    url: jdbc:mysql://db-test-app-service/dbtestapp
    username: userMWW
    password: cAeIUceaG45SYyf2
    #url: jdbc:mysql://localhost/test
    #username: root
    #password: admin1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    show-sql: true
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    cache: false
server:
  port: 8080
  #port: 1234